# ============================================================================
#
# 默认生成的配置旨在突出 Zensical 提供的功能，并作为您自己项目的起点。
#
# ============================================================================

[project]

# site_name 显示在页面标题栏和浏览器窗口标题中。
#
# 了解更多：https://zensical.org/docs/setup/basics/#site_name
site_name = "xy的web"

# site_description 包含在 HTML head 中，应为搜索引擎提供有意义的站点内容描述。
#
# 了解更多：https://zensical.org/docs/setup/basics/#site_description
site_description = "cqxy.qzz.io"

# site_author 属性。用于 HTML head 元素。
#
# 了解更多：https://zensical.org/docs/setup/basics/#site_author
site_author = "xy"

# site_url 是您站点的规范 URL。在构建在线文档时应设置此项。
# 了解更多：https://zensical.org/docs/setup/basics/#site_url
site_url = "https://cqxy.qzz.io/xy-site"

# copyright 显示在页面页脚，可以包含 HTML 片段。
#
# 了解更多：https://zensical.org/docs/setup/basics/#copyright
copyright = """
Copyright &copy; 2026 xy
"""

# Zensical 支持隐式导航和显式定义的导航。
# 如果您决定不在此定义导航，那么 Zensical 将简单地根据您的
# "docs_dir" 的目录结构推导导航结构。下面的定义演示了如何使用
# TOML 语法定义导航结构。
#
# 了解更多：https://zensical.org/docs/setup/navigation/
nav = [
 "index.md",
{"Bookmark" = [
        "Bookmark/index.md",
        "Bookmark/system-tools.md",
        "Bookmark/minecraft.md",
        "Bookmark/github.md",
        "Bookmark/free-game.md",
        "Bookmark/lx-music.md",
        "Bookmark/other-music.md",
        "Bookmark/others.md",
]},
{"How to Write" = [
        "Markdown/How to write.md",
        "Markdown/markdown.md",
]},
{"Class logs of 4"=[
    "Class 4/index.md",
    "Class 4/2026-03.md",
]},
{"Skills"=[
    "skills/index.md",
    "skills/破解希沃冰点.md",
]},
 "about.md",
]

# 通过 "extra_css" 选项，您可以添加自己的 CSS 样式，根据您的需求
# 自定义 Zensical 项目。您可以添加任意数量的 CSS 文件。
#
# 提供的路径应相对于 "docs_dir"。
#
# 了解更多：https://zensical.org/docs/customization/#additional-css
#
#extra_css = ["stylesheets/extra.css"]

# 通过 "extra_javascript" 选项，您可以添加自己的 JavaScript 到项目中，
# 根据需要自定义行为。
#
# 提供的路径应相对于 "docs_dir"。
#
# 了解更多：https://zensical.org/docs/customization/#additional-javascript
#extra_javascript = ["javascripts/extra.js"]

# ----------------------------------------------------------------------------
# 配置主题选项的章节
# ----------------------------------------------------------------------------
[project.theme]

# 将此更改为 "classic" 可使用传统的 Material for MkDocs 外观。
variant = "modern"

# Zensical 允许您覆盖特定的块、局部模板或整个模板，以及定义自己的模板。
# 要执行此操作，请取消下面的 custom_dir 设置，并将其设置为存放
# 模板覆盖文件的目录。
#
# 了解更多：
# - https://zensical.org/docs/customization/#extending-the-theme
#
#custom_dir = "overrides"

# 使用 "favicon" 选项，您可以设置自己的图像作为浏览器在标题栏或选项卡中
# 使用的图标。提供的路径必须相对于 "docs_dir"。
#
# 了解更多：
# - https://zensical.org/docs/setup/logo-and-icons/#favicon
# - https://developer.mozilla.org/en-US/docs/Glossary/Favicon
#
favicon = "images/favicon.png"

# Zensical 支持超过 60 种不同的语言。这意味着 Zensical 模板生成的标签和
# 工具提示都会被翻译。"language" 选项允许您设置使用的语言。此语言
# 也会在 HTML head 元素中指示，以帮助无障碍访问并指导搜索引擎和翻译工具。
#
# 默认语言为 "en"（英语）。可以创建多语言站点并配置语言选择器。详情
# 请参阅文档。
#
# 了解更多：
# - https://zensical.org/docs/setup/language/
#
language = "zh"

# Zensical 提供许多功能开关，用于改变文档站点的行为。
features = [
    # Zensical 包含一个公告栏。此功能允许用户在阅读公告后将其关闭。
    # https://zensical.org/docs/setup/header/#announcement-bar
    "announce.dismiss",

    # 如果您配置了仓库并开启此功能，Zensical 将为页面生成一个编辑按钮。
    # 这适用于常见的仓库托管服务。
    # https://zensical.org/docs/setup/repository/#content-actions
    "content.action.edit",

    # 如果您配置了仓库并开启此功能，Zensical 将生成一个按钮，允许用户
    # 查看当前页面的 Markdown 源码。
    # https://zensical.org/docs/setup/repository/#content-actions
    #"content.action.view",

    # 代码注解允许您在代码块中添加一个带有工具提示的图标，以便在关键点提供解释。
    # https://zensical.org/docs/authoring/code-blocks/#code-annotations
    "content.code.annotate",

    # 此功能在代码块中开启一个按钮，允许用户将内容复制到剪贴板，无需先选中。
    # https://zensical.org/docs/authoring/code-blocks/#code-copy-button
    "content.code.copy",

    # 代码块可以包含一个按钮，允许用户选择行范围。
    # https://zensical.org/docs/authoring/code-blocks/#code-selection-button
    "content.code.select",

    # Zensical 可以将脚注渲染为内联工具提示，让用户无需离开文档上下文即可阅读脚注。
    # https://zensical.org/docs/authoring/footnotes/#footnote-tooltips
    "content.footnote.tooltips",

    # 如果您有许多标题相同的内容选项卡（例如 "Python"、"JavaScript"、"Cobol"），
    # 此功能会使所有选项卡在用户选择一个语言后同步切换。
    # https://zensical.org/docs/authoring/content-tabs/#linked-content-tabs
    "content.tabs.link",

    # 启用此功能后，用户可以为链接添加工具提示，当鼠标悬停时显示。
    # https://zensical.org/docs/authoring/tooltips/#improved-tooltips
    "content.tooltips",

    # 启用此功能后，Zensical 会在用户滚动超过某个点时自动隐藏页眉的部分区域。
    # https://zensical.org/docs/setup/header/#automatic-hiding
    # "header.autohide",

    # 开启此功能可默认展开导航侧边栏中所有可折叠部分。
    # https://zensical.org/docs/setup/navigation/#navigation-expansion
    # "navigation.expand",

    # 此功能在页脚中启用导航元素，允许用户导航到上一页或下一页。
    # https://zensical.org/docs/setup/footer/#navigation
    "navigation.footer",

    # 启用章节索引页时，文档可以直接附加到章节，这对提供概览页面特别有用。
    # https://zensical.org/docs/setup/navigation/#section-index-pages
    "navigation.indexes",

    # 启用即时导航时，所有内部链接的点击将被拦截并通过 XHR 调度，无需完全重新加载页面。
    # https://zensical.org/docs/setup/navigation/#instant-navigation
    "navigation.instant",

    # 使用即时预取，您的站点将在用户悬停在链接上时开始获取页面。这将减少用户的感知加载时间。
    # https://zensical.org/docs/setup/navigation/#instant-prefetching
    "navigation.instant.prefetch",

    # 为了在使用即时导航时在慢速连接上提供更好的用户体验，可以启用进度指示器。
    # https://zensical.org/docs/setup/navigation/#progress-indicator
    #"navigation.instant.progress",

    # 启用导航路径时，每个页面的标题上方会渲染一个面包屑导航。
    # https://zensical.org/docs/setup/navigation/#navigation-path
    "navigation.path",

    # 启用剪裁时，只有可见的导航项会包含在渲染的 HTML 中，使构建的站点大小减少 33% 或更多。
    # https://zensical.org/docs/setup/navigation/#navigation-pruning
    #"navigation.prune",

    # 启用章节时，顶层章节在视口宽度超过 1220px 时会在侧边栏中渲染为分组，在移动设备上保持不变。
    # https://zensical.org/docs/setup/navigation/#navigation-sections
    "navigation.sections",

    # 启用选项卡时，顶层章节在视口宽度超过 1220px 时会在页眉下方渲染为菜单层，在移动设备上保持不变。
    # https://zensical.org/docs/setup/navigation/#navigation-tabs
    "navigation.tabs",

    # 启用固定选项卡时，导航选项卡将锁定在页眉下方，滚动时始终保持可见。
    # https://zensical.org/docs/setup/navigation/#sticky-navigation-tabs
    #"navigation.tabs.sticky",

    # 当用户向下滚动后又开始向上滚动时，可以显示一个返回顶部的按钮。
    # https://zensical.org/docs/setup/navigation/#back-to-top-button
    "navigation.top",

    # 启用锚点跟踪时，地址栏中的 URL 会自动更新为目录中高亮显示的活动锚点。
    # https://zensical.org/docs/setup/navigation/#anchor-tracking
    "navigation.tracking",

    # 启用搜索高亮后，当用户点击搜索结果时，Zensical 会在跟随链接后高亮所有出现的位置。
    # https://zensical.org/docs/setup/search/#search-highlighting
    "search.highlight",

    # 启用目录的锚点跟随功能后，侧边栏会自动滚动，使活动锚点始终可见。
    # https://zensical.org/docs/setup/navigation/#anchor-following
    # "toc.follow",

    # 启用目录的导航集成功能后，目录始终作为左侧导航侧边栏的一部分渲染。
    # https://zensical.org/docs/setup/navigation/#navigation-integration
    #"toc.integrate",
]

# ----------------------------------------------------------------------------
# 您可以使用 "theme" 子部分中的 "logo" 选项配置自己的徽标，显示在页眉中。
# 徽标必须是 "docs_dir" 中文件的相对路径，例如，要使用 `docs/assets/logo.png`，
# 您可以设置：
# ----------------------------------------------------------------------------
#logo = "assets/logo.png"

# ----------------------------------------------------------------------------
# 如果您没有专门的项目徽标，可以使用 Zensical 附带的图标集中的内置图标。
# 请注意，该设置位于不同的子部分，且上述设置优先于图标。
#
# 了解更多：
# - https://zensical.org/docs/setup/logo-and-icons
# - https://github.com/zensical/ui/tree/master/dist/.icons
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"

# ----------------------------------------------------------------------------
# 在 "font" 子部分中，您可以配置使用的字体。默认情况下，字体从 Google Fonts
# 加载，为您提供一系列适当许可的字体供选择。普通文本字体和代码块中使用的
# 等宽字体各有选项。
# ----------------------------------------------------------------------------
#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# 在 "palette" 子部分中，您可以配置颜色方案的选项。
# 您可以配置不同的颜色方案，例如开启暗色模式，让用户切换。
# 每个颜色方案可以进一步自定义。
#
# 了解更多：
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "切换到暗色模式"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "切换到亮色模式"

[project.extra] 
# ----------------------------------------------------------------------------
# "extra" 部分包含各种杂项设置。
# ----------------------------------------------------------------------------
    [[project.extra.social]]
    icon = "fontawesome/brands/github"
    link = "https://github.com/gyhut2/xy-site"
    name = "在 GitHub 上查看源码"

    [[project.extra.social]]
    icon = "fontawesome/brands/qq"
    link = "/#"
    name = "3995981608"